In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

In [2]:
# from sklearn.datasets import fetch_california_housing

In [3]:
# from sklearn.datasets import fetch_california_housing
import pandas as pd
df = pd.read_csv("file.csv")
# df = fetch_california_housing()

In [4]:
df.keys()

Index(['QUOTE_DATE', 'CustomerID', 'ITEM_DESC', 'VALIDITY', 'SHOP_CODE',
       'PRICE', 'INDICATOR_BOX', 'ORIG_INDICATOR_BOX', 'PRICE_RELATIVE',
       'LOG_PRICE_RELATIVE', 'STRATUM_WEIGHT', 'STRATUM_TYPE', 'START_DATE',
       'END_DATE', 'QUANTITY', 'SHOP_TYPE', 'SHOP_WEIGHT', 'BASE_PRICE',
       'BASE_VALIDITY', 'STRATUM_CELL'],
      dtype='object')

In [5]:
import pandas as pd
print(df.describe())

       QUOTE_DATE     CustomerID       VALIDITY      SHOP_CODE          PRICE  \
count    139419.0  139419.000000  139419.000000  139419.000000  139419.000000   
mean     202301.0  376649.778997       2.895509    1040.958765      53.166161   
std           0.0  149600.411234       0.648717    2898.435704     250.069136   
min      202301.0  210102.000000       1.000000       1.000000       0.000000   
25%      202301.0  212712.000000       3.000000      41.000000       1.350000   
50%      202301.0  430127.000000       3.000000      92.000000       4.450000   
75%      202301.0  510349.000000       3.000000     904.000000      17.600000   
max      202301.0  640406.000000       4.000000   18550.000000   21000.000000   

       PRICE_RELATIVE  LOG_PRICE_RELATIVE  STRATUM_WEIGHT   STRATUM_TYPE  \
count   139419.000000       139419.000000   139419.000000  139419.000000   
mean         1.026850            0.081656       29.656106       1.844254   
std          0.433982            0.234952 

In [6]:
data=df.data.columns.str.strip()
print(df.data)
# print(df.target)
# print(df.feature_names)

AttributeError: 'DataFrame' object has no attribute 'data'

In [437]:
dataset=pd.DataFrame(df.data,columns=df.feature_names)

In [438]:
dataset['Price']=df.target

In [ ]:
dataset.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [ ]:
dataset.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   
Price       0.688075  0.105623  0.151948  -0.046701   -0.024650 -0.023737   

            Latitude  Longitude     Price  
MedInc     -0.079809  -0.015176  0.688075  
HouseAge    0.011173  -0.108197  0.105623  
AveRooms    0.106389  -0.027540  0.151948  
AveBedrms   0.069721   0.013344 -0.046701  
Population -0.108785   0.099773 -0.024650  
AveOccup    0.002366   0.002476 -0.023737  
Latitude    1.000000  -0.924664 -0.144160  
Longitude  -0.924664   1.000000 -0.045967  
Price      -0.144160  -0.045967  1.000000

In [441]:
# %pip install seaborn
# import seaborn as sns
# sns.pairplot(dataset)

In [442]:
dataset.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   
Price       0.688075  0.105623  0.151948  -0.046701   -0.024650 -0.023737   

            Latitude  Longitude     Price  
MedInc     -0.079809  -0.015176  0.688075  
HouseAge    0.011173  -0.108197  0.105623  
AveRooms    0.106389  -0.027540  0.151948  
AveBedrms   0.069721   0.013344 -0.046701  
Population -0.108785   0.099773 -0.024650  
AveOccup    0.002366   0.002476 -0.023737  
Latitude    1.000000  -0.924664 -0.144160  
Longitude  -0.924664   1.000000 -0.045967  
Price      -0.144160  -0.045967  1.000000

In [443]:
# plt.scatter(dataset['CRIM'],dataset['Price'])
# plt.xlabel("Crime Rate")
# plt.ylabel("Price")

In [444]:
# plt.scatter(dataset['RM'],dataset['Price'])
# plt.xlabel("RM")
# plt.ylabel("Price")

In [445]:
# import seaborn as sns
# sns.regplot(x="RM",y="Price",data=dataset)

In [446]:
# sns.regplot(x="LSTAT",y="Price",data=dataset)

In [447]:
# sns.regplot(x="CHAS",y="Price",data=dataset)

In [448]:
# sns.regplot(x="PTRATIO",y="Price",data=dataset)

In [449]:
X=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [450]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [451]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

In [452]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [453]:
X_train

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
7061   4.1312      35.0  5.882353   0.975490      1218.0  2.985294     33.93   
14689  2.8631      20.0  4.401210   1.076613       999.0  2.014113     32.79   
17323  4.2026      24.0  5.617544   0.989474       731.0  2.564912     34.59   
10056  3.1094      14.0  5.869565   1.094203       302.0  2.188406     39.26   
15750  3.3068      52.0  4.801205   1.066265      1526.0  2.298193     37.77   
...       ...       ...       ...        ...         ...       ...       ...   
11284  6.3700      35.0  6.129032   0.926267       658.0  3.032258     33.78   
11964  3.0500      33.0  6.868597   1.269488      1753.0  3.904232     34.02   
5390   2.9344      36.0  3.986717   1.079696      1756.0  3.332068     34.03   
860    5.7192      15.0  6.395349   1.067979      1777.0  3.178891     37.58   
15795  2.5755      52.0  3.402576   1.058776      2619.0  2.108696     37.77   

       Longitude  
7061     -118.02  
14689    -117.09  
17323    -120.14  
10056    -121.00  
15750    -122.45  
...          ...  
11284    -117.96  
11964    -117.43  
5390     -118.38  
860      -121.96  
15795    -122.42  

[14448 rows x 8 columns]

In [454]:
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20046  1.6812      25.0  4.192201   1.022284      1392.0  3.877437     36.06   
3024   2.5313      30.0  5.039384   1.193493      1565.0  2.679795     35.14   
15663  3.4801      52.0  3.977155   1.185877      1310.0  1.360332     37.80   
20484  5.7376      17.0  6.163636   1.020202      1705.0  3.444444     34.28   
9814   3.7250      34.0  5.492991   1.028037      1063.0  2.483645     36.62   
...       ...       ...       ...        ...         ...       ...       ...   
17505  2.9545      47.0  4.195833   1.020833       581.0  2.420833     37.36   
13512  1.4891      41.0  4.551852   1.118519       994.0  3.681481     34.11   
10842  3.5120      16.0  3.762287   1.075614      5014.0  2.369565     33.67   
16559  3.6500      10.0  5.502092   1.060371      5935.0  3.547519     37.82   
5786   3.0520      17.0  3.355781   1.019695      4116.0  2.614994     34.15   

       Longitude  
20046    -119.01  
3024     -119.46  
15663    -122.44  
20484    -118.72  
9814     -121.93  
...          ...  
17505    -121.90  
13512    -117.32  
10842    -117.91  
16559    -121.28  
5786     -118.24  

[6192 rows x 8 columns]

In [455]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [456]:
X_train=scaler.fit_transform(X_train)

In [457]:
X_test=scaler.transform(X_test)

In [458]:
import pickle
pickle.dump(scaler,open('scaling.pkl','wb'))

In [459]:
X_train

array([[ 0.13350629,  0.50935748,  0.18106017, ..., -0.01082519,
        -0.80568191,  0.78093406],
       [-0.53221805, -0.67987313, -0.42262953, ..., -0.08931585,
        -1.33947268,  1.24526986],
       [ 0.1709897 , -0.36274497,  0.07312833, ..., -0.04480037,
        -0.49664515, -0.27755183],
       ...,
       [-0.49478713,  0.58863952, -0.59156984, ...,  0.01720102,
        -0.75885816,  0.60119118],
       [ 0.96717102, -1.07628333,  0.39014889, ...,  0.00482125,
         0.90338501, -1.18625198],
       [-0.68320166,  1.85715216, -0.82965604, ..., -0.0816717 ,
         0.99235014, -1.41592345]], shape=(14448, 8))

In [460]:
X_test

array([[-1.1526893 , -0.28346293, -0.50781822, ...,  0.06127763,
         0.19166399,  0.28664112],
       [-0.70640568,  0.11294728, -0.16252032, ..., -0.03551561,
        -0.23911452,  0.06196251],
       [-0.20830675,  1.85715216, -0.59546738, ..., -0.14215427,
         1.00639726, -1.42590916],
       ...,
       [-0.19155996, -0.99700129, -0.6830438 , ..., -0.06058827,
        -0.92742367,  0.8358555 ],
       [-0.11911302, -1.47269353,  0.02607207, ...,  0.03461374,
         1.01576201, -0.84673764],
       [-0.43304974, -0.91771925, -0.84872893, ..., -0.0407528 ,
        -0.70266966,  0.67109119]], shape=(6192, 8))

In [461]:
from sklearn.linear_model import LinearRegression

In [462]:
regression=LinearRegression()

In [463]:
regression.fit(X_train,y_train)

LinearRegression()

In [464]:
print(regression.coef_)

[ 8.49221760e-01  1.22119309e-01 -2.99558449e-01  3.48409673e-01
 -8.84488134e-04 -4.16980388e-02 -8.93855649e-01 -8.68616688e-01]


In [465]:
print(regression.intercept_)

2.0692396089424165


In [466]:

regression.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [467]:

reg_pred=regression.predict(X_test)

In [468]:
reg_pred

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133], shape=(6192,))

In [469]:

# plt.scatter(y_test,reg_pred)

In [470]:

residuals=y_test-reg_pred

In [471]:
residuals

20046   -0.249049
3024    -1.309434
15663    2.289088
20484   -0.649147
9814     0.173042
           ...   
17505    0.155059
13512   -0.237516
10842    0.109345
16559   -0.379714
5786     0.270559
Name: Price, Length: 6192, dtype: float64

In [472]:
# sns.displot(residuals,kind="kde")

In [473]:
# plt.scatter(reg_pred,residuals)

In [474]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

0.5272474538305952
0.5305677824766752
0.7284008391515452


In [475]:
from sklearn.metrics import r2_score
score=r2_score(y_test,reg_pred)
print(score)

0.5957702326061665


In [476]:
1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.5952472117200027

In [477]:
df.data[0].reshape(1,-1)

array([[   8.3252    ,   41.        ,    6.98412698,    1.02380952,
         322.        ,    2.55555556,   37.88      , -122.23      ]])

In [478]:
scaler.transform(df.data[0].reshape(1,-1))

c:\python21\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 2.33526315,  0.98504972,  0.63012521, -0.16586931, -0.96995366,
        -0.04555657,  1.04385626, -1.32105914]])

In [479]:
regression.predict(scaler.transform(df.data[0].reshape(1,-1)))

c:\python21\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([4.14333441])

In [480]:
import pickle

In [481]:
pickle.dump(regression,open('regmodel.pkl','wb'))

In [482]:
pickled_model=pickle.load(open('regmodel.pkl','rb'))

In [483]:
pickled_model.predict(scaler.transform(df.data[0].reshape(1,-1)))

c:\python21\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([4.14333441])